### ISSUE TITLE
Card: A11y considerations

### ISSUE THREAD

**Issue by camfindlay** [data-govt-nz/rua#4]
The card semantic markup is something we've spent time sorting on the current site to best meet accessibility and usability guidelines (and practicalities). Suggest reviewing the card like markup on the home page of the current theme.

Key things are:
 - The image is clickable
 - It includes categories if needed (we can use our existing tags component as a variation).
 - The "alt" attributes should be included for images and these should describe whats on the next page rather that what the image is.
- To get this to play nice with screen readers you need to wrap both the img and heading tags in the a tag (it might make you cringe semantically but this is workable good practice for this scenario put forward by an a11y expert and previous w3c rep we work with :+1:).

**Comment by camfindlay** [comment]
https://data-govt-nz.github.io/rua/section-informationcomponents.html#kssref-informationcomponents-card

**Comment by gorriecoe** [comment]
Updated as of https://github.com/data-govt-nz/rua/commit/05ce07fe91984f663347b6b06117754b58eb22ed
