### ISSUE TITLE
Headings and breadcrumb: Size considerations with real world content

### ISSUE THREAD

**Issue by camfindlay** [data-govt-nz/rua#9]
Not that the headings in the hero banner when we have longer real world text in place end up pushing off screen. Breadcrumb also get cut off.

@gorriecoe you might need to revisit the sizes of the heading elements or find some way to make them more relative to their context.

Example:

![heading-size-issues](https://user-images.githubusercontent.com/367847/48923507-05c54980-ef14-11e8-873b-af73bb21d4cd.JPG)

**Comment by gorriecoe** [comment]
Ok had a chat with Andrew and we will try allowing the height to increase and ellipsis the breadcrumbs.
